version: '3.4'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=./api-gateway/build/libs/*.jar
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=./web-demo/build/libs/*.jar
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    depends_on:
      - demo-app
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  k6:
    image: loadimpact/k6:latest
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6-scripts:/scripts

